### ISSUE TITLE
WorkManager Issue

### ISSUE THREAD

**Issue by tiduz007** [algolia/instantsearch-android-insights#10]
Fatal Exception: java.lang.RuntimeException: Unable to create application com.myapp.app.MyApplication: java.lang.IllegalStateException: WorkManager is not initialized properly.  The most likely cause is that you disabled WorkManagerInitializer in your manifest but forgot to call WorkManager#initialize in your Application#onCreate or a ContentProvider.
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4824)
       at android.app.ActivityThread.access$1600(ActivityThread.java:157)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1417)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5551)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:734)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:624)

**Comment by q-litzler** [comment]
Hello, can you please tell us which version of the library you are using, and show us a piece of your code demonstrating how you've been using it ?

**Comment by q-litzler** [comment]
Please reopen if you have more information.
